---
apiVersion: v1
kind: Service
metadata:
  name: kasa-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kasa-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kasa-exporter
  ports:
    - port: 9907
      targetPort: http
      name: http
      protocol: TCP
