[project]
name = "kasa-exporter"
version = "0.2.2"
description = ""
authors = [{ name = "Tom Helander", email = "thomas.helander@gmail.com" }]
dependencies = [
    "python-kasa>=0.6.2.1",
    "prometheus-client>=0.20.0",
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.28.0",
]
requires-python = ">=3.14"

[project.optional-dependencies]
speedups = ["python-kasa[speedups]"]

[project.scripts]
kasa-exporter = "kasa_exporter.app:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13"]
build-backend = "uv_build"
